export const songJson = [
    {number: 0,"artist":"ABBA","song":"Ahe's My Kind Of Girl"},
    {number: 1,"artist":"ABBA","song":"Andante, Andante"},
    {number: 2,"artist":"ABBA","song":"As Good As New"},
    {number: 3,"artist":"ABBA","song":"Bang"},
    {number: 4,"artist":"ABBA","song":"Bang-A-Boomerang"},
    {number: 5,"artist":"ABBA","song":"Burning My Bridges"},
    {number: 6,"artist":"ABBA","song":"Cassandra"},
    {number: 7,"artist":"ABBA","song":"Chiquitita"},
    {number: 8,"artist":"ABBA","song":"Crazy World"},
    {number: 9,"artist":"ABBA","song":"Crying Over You"},
    {number: 10,"artist":"ABBA","song":"Dance"},
    {number: 11,"artist":"ABBA","song":"Dancing Queen"},
    {number: 12,"artist":"ABBA","song":"Disillusion"},
    {number: 13,"artist":"ABBA","song":"Does Your Mother Know"},
    {number: 14,"artist":"ABBA","song":"Dream World"},
    {number: 15,"artist":"ABBA","song":"Dum Dum Diddle"},
    {number: 16,"artist":"ABBA","song":"Eagle"},
    {number: 17,"artist":"ABBA","song":"Every Good Man"},
    {number: 18,"artist":"ABBA","song":"Fernando"},
    {number: 19,"artist":"ABBA","song":"Fernando (In Spanish)"},
    {number: 20,"artist":"ABBA","song":"Free As A Bumble Bee"},
    {number: 21,"artist":"ABBA","song":"From A Twinkling Star To A Passing Angel"},
    {number: 22,"artist":"ABBA","song":"Gimme Gimme Gimme"},
    {number: 23,"artist":"ABBA","song":"Givin' A Little Bit More"},
    {number: 24,"artist":"ABBA","song":"Gonna Sing You My Lovesong"},
    {number: 25,"artist":"ABBA","song":"Hamlet III"},
    {number: 26,"artist":"ABBA","song":"Happy Hawaii"},
    {number: 27,"artist":"ABBA","song":"Happy New Year"},
    {number: 28,"artist":"ABBA","song":"He Is Your Brother"},
    {number: 29,"artist":"ABBA","song":"Head Over Heels"},
    {number: 30,"artist":"ABBA","song":null},
    {number: 31,"artist":"ABBA","song":"Hey Hey Helen"},
    {number: 32,"artist":"ABBA","song":"Hole In Your Soul"},
    {number: 33,"artist":"ABBA","song":"Honey, Honey"},
    {number: 34,"artist":"ABBA","song":"I Am Just A Girl"},
    {number: 35,"artist":"ABBA","song":"I Am The City"},
    {number: 36,"artist":"ABBA","song":"I Do, I Do, I Do, I Do, I Do"},
    {number: 37,"artist":"ABBA","song":"I Have A Dream"},
    {number: 38,"artist":"ABBA","song":"I Let The Music Speak"},
    {number: 39,"artist":"ABBA","song":"I Saw It In The Mirror"},
    {number: 40,"artist":"ABBA","song":"I Wonder (Departure)"},
    {number: 41,"artist":"ABBA","song":"I Wonder (Departure) [Live]"},
    {number: 42,"artist":"ABBA","song":"If It Wasn't For The Nights"},
    {number: 43,"artist":"ABBA","song":"I'm A Marionette"},
    {number: 44,"artist":"ABBA","song":"I've Been Waiting For You"},
    {number: 45,"artist":"ABBA","song":"Juper Jrouper"},
    {number: 46,"artist":"ABBA","song":"Just A Notion"},
    {number: 47,"artist":"ABBA","song":"King Kong Song"},
    {number: 48,"artist":"ABBA","song":"Kisses Of Fire"},
    {number: 49,"artist":"ABBA","song":"Knowing Me Knowing You"},
    {number: 50,"artist":"ABBA","song":"Lay All Your Love On Me"},
    {number: 51,"artist":"ABBA","song":"Like An Angel Passing Through My Room"},
    {number: 52,"artist":"ABBA","song":"Love Has It's Ways"},{"artist":"ABBA","song":"Love Isn't Easy"},
    {number: 53,"artist":"ABBA","song":"Lovelight"},
    {number: 54,"artist":"ABBA","song":"Lovers"},
    {number: 55,"artist":"ABBA","song":"Mamma Mia"},
    {number: 56,"artist":"ABBA","song":"Man In The Middle"},
    {number: 57,"artist":"ABBA","song":"Me And Bobby And Bobby's Brother"},
    {number: 58,"artist":"ABBA","song":"Me And I"},
    {number: 59,"artist":"ABBA","song":"Merry-Go-Round"},
    {number: 60,"artist":"ABBA","song":"Midnight Special"},
    {number: 61,"artist":"ABBA","song":"Money Money Money"},
    {number: 62,"artist":"ABBA","song":"Move On"},
    {number: 63,"artist":"ABBA","song":"My Love, My Life"},
    {number: 64,"artist":"ABBA","song":"My Mama Said"},
    {number: 65,"artist":"ABBA","song":"Nina, Pretty Ballerina"},
    {number: 66,"artist":"ABBA","song":"On And On And On"},
    {number: 67,"artist":"ABBA","song":"One Man, One Woman"},
    {number: 68,"artist":"ABBA","song":"One Of Us"},
    {number: 69,"artist":"ABBA","song":"Our Last Summer"},
    {number: 70,"artist":"ABBA","song":"People Need Love"},
    {number: 71,"artist":"ABBA","song":"Pick A Bale Of Cotton"},
    {number: 72,"artist":"ABBA","song":"Put On Your White Sombrero"},
    {number: 73,"artist":"ABBA","song":"Reina Danzante"},
    {number: 74,"artist":"ABBA","song":"Rikky Rock'n'Roller"},
    {number: 75,"artist":"ABBA","song":"Ring Ring"},
    {number: 76,"artist":"ABBA","song":"Rock Me"},
    {number: 77,"artist":"ABBA","song":"Rock 'n Roll Band"},
    {number: 78,"artist":"ABBA","song":"Rubber Ball Man"},
    {number: 79,"artist":"ABBA","song":"S. O. S."},
    {number: 80,"artist":"ABBA","song":"Should I Laugh Or Cry"},
    {number: 81,"artist":"ABBA","song":"Sitting In The Palmtree"},
    {number: 82,"artist":"ABBA","song":"Slipping Through My Fingers"},
    {number: 83,"artist":"ABBA","song":"So Long"},
    {number: 84,"artist":"ABBA","song":"Soldiers"},
    {number: 85,"artist":"ABBA","song":"SOS"},
    {number: 86,"artist":"ABBA","song":"Summer Night City"},
    {number: 87,"artist":"ABBA","song":"Suzy-Hang-Around"},
    {number: 88,"artist":"ABBA","song":"Take A Chance"},
    {number: 89,"artist":"ABBA","song":"Take A Chance On Me"},
    {number: 90,"artist":"ABBA","song":"Thank You For The Music"},
    {number: 91,"artist":"ABBA","song":"That's Me"},
    {number: 92,"artist":"ABBA","song":"The Day Before You Came"},
    {number: 93,"artist":"ABBA","song":"The King Has Lost His Crown"},
    {number: 94,"artist":"ABBA","song":"The Name Of The Game"},
    {number: 95,"artist":"ABBA","song":"The Piper"},
    {number: 96,"artist":"ABBA","song":"The Visitors"},
    {number: 97,"artist":"ABBA","song":"The Way Old Friends Do"},
    {number: 98,"artist":"ABBA","song":"The Winner Takes It All"},
    {number: 99,"artist":"ABBA","song":"Tiger"}]